Level
zimme95/thundercats pull request #31
Opened 2018-05-20 22:04 UTC by Axellent

2018-05-21 05:38 UTC, simon-f-kevin approved these changes
Måste CollisionActions innehålla hårdkodade värden för förändring av hastighet?

NetworkInputSystem är deprecated tror jag.

2018-05-21 05:54 UTC, Axellent commented
Det är så jag justerat just nu då gametime i normala fall kommer multiplicera med väldigt låga värden. Hittar ni en smartare formel så förbättta gärna

2018-05-21 13:31 UTC, JBMATANDA approved these changes

2018-05-23 09:22 UTC, simon-f-kevin requested changes
Jag testade att mergea min egen branch med level/gametime branchen och märkte att fysiken ballar ur totalt, vi rör oss extremt fort och hoppar oändligt högt. Kan du se över detta innan vi mergear in den i master.

2018-05-24 23:48 UTC, merged